# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoEmojify < Formula
  desc "Yet another emojify command written in Go "
  homepage "https://github.com/yusukebe/go-emojify"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yusukebe/go-emojify/releases/download/v0.1.5/go-emojify_Darwin_arm64_v0.1.5.tar.gz"
      sha256 "f8f191133c3cd2c6f071b1d83b23943d29f0f760c4d08c6c1d30be0e36fb8d45"

      def install
        bin.install "go-emojify"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yusukebe/go-emojify/releases/download/v0.1.5/go-emojify_Darwin_x86_64_v0.1.5.tar.gz"
      sha256 "5e211541c58825afc4c0e26048880b51db9b0225f6f1a8aad00d8bc2ee189463"

      def install
        bin.install "go-emojify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/yusukebe/go-emojify/releases/download/v0.1.5/go-emojify_Linux_arm_v0.1.5.tar.gz"
      sha256 "461e9ede60e0864a358b3f31c2ad4e39eff2319c565bd1e6874c768ac11c6429"

      def install
        bin.install "go-emojify"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yusukebe/go-emojify/releases/download/v0.1.5/go-emojify_Linux_x86_64_v0.1.5.tar.gz"
      sha256 "3203dad450b13c9a6d25d05793024ced2f65b201f658c42ad923fc314842704a"

      def install
        bin.install "go-emojify"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yusukebe/go-emojify/releases/download/v0.1.5/go-emojify_Linux_arm64_v0.1.5.tar.gz"
      sha256 "010bff7ce73fa9ae38ef3a2c6e150696d994ed603caa099df9ae75a6f8e68cae"

      def install
        bin.install "go-emojify"
      end
    end
  end
end
