# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoEmojify < Formula
  desc "Yet another emojify command written in Go "
  homepage "https://github.com/yusukebe/go-emojify"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yusukebe/go-emojify/releases/download/v0.1.5/go-emojify_Darwin_x86_64_v0.1.5.tar.gz"
      sha256 "e7c9f86c63378042512bf36484603698e478a52e6d7630acdf27e53c245d3482"

      def install
        bin.install "go-emojify"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yusukebe/go-emojify/releases/download/v0.1.5/go-emojify_Darwin_arm64_v0.1.5.tar.gz"
      sha256 "49fb0413c7e8525094ceaced0d097538a0274cc89f2002b960142b8af896b0db"

      def install
        bin.install "go-emojify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yusukebe/go-emojify/releases/download/v0.1.5/go-emojify_Linux_arm64_v0.1.5.tar.gz"
      sha256 "fb5ac7ea19def883ae771748a8ebcc07df944099d73dbc1e88626e3cab0882ca"

      def install
        bin.install "go-emojify"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yusukebe/go-emojify/releases/download/v0.1.5/go-emojify_Linux_x86_64_v0.1.5.tar.gz"
      sha256 "bdcd7a4b8323a38de78322292fb8ff4762ae737afa781f6f89cb5a9cd9b30adc"

      def install
        bin.install "go-emojify"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/yusukebe/go-emojify/releases/download/v0.1.5/go-emojify_Linux_arm_v0.1.5.tar.gz"
      sha256 "6664df731c25050598723ee561cb6fbeb99f08ac34299924bae8e17d17590669"

      def install
        bin.install "go-emojify"
      end
    end
  end
end
