# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Revealgo < Formula
  desc "Markdown driven presentation tool written in Go!"
  homepage "https://github.com/yusukebe/revealgo"
  version "1.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yusukebe/revealgo/releases/download/v1.2.1/revealgo_1.2.1_macOS-ARM64.tar.gz"
      sha256 "3a5d1f3a718cec97786fc7f53376d0df6332942c1c1bf6f0eef95bddefc11f1a"

      def install
        bin.install "revealgo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yusukebe/revealgo/releases/download/v1.2.1/revealgo_1.2.1_macOS-64bit.tar.gz"
      sha256 "9f30f80e685197ce3d33f181c7111ceb9da7b6d5a031c7e4d5322e52d45f3eb4"

      def install
        bin.install "revealgo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yusukebe/revealgo/releases/download/v1.2.1/revealgo_1.2.1_Linux-ARM64.tar.gz"
      sha256 "765a504ccc1ee040183cded30138a81979dd0be1e79d56d01063d32931824b50"

      def install
        bin.install "revealgo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yusukebe/revealgo/releases/download/v1.2.1/revealgo_1.2.1_Linux-64bit.tar.gz"
      sha256 "caf342cc59b6a1063d27d46b1060b34f47b2794d1fd7eca052966a166aaebb0b"

      def install
        bin.install "revealgo"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/yusukebe/revealgo/releases/download/v1.2.1/revealgo_1.2.1_Linux-ARM.tar.gz"
      sha256 "e1ba8eb66d2a4ae953d9bfbe49ca94e2266addf960da2605fbf8eb6ef0fb4d36"

      def install
        bin.install "revealgo"
      end
    end
  end
end
