# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Revealgo < Formula
  desc "Markdown driven presentation tool written in Go!"
  homepage "https://github.com/yusukebe/revealgo"
  version "1.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yusukebe/revealgo/releases/download/v1.2.1/revealgo_1.2.1_macOS-ARM64.tar.gz"
      sha256 "7c0ec12c68d0a43a7560606696f5269a64439f5784535a84d2f8daff18f37d5a"

      def install
        bin.install "revealgo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yusukebe/revealgo/releases/download/v1.2.1/revealgo_1.2.1_macOS-64bit.tar.gz"
      sha256 "f9bf7adcbb927c8b2628d53a7139383cfca550adb150043a6408cff6920d2d4e"

      def install
        bin.install "revealgo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/yusukebe/revealgo/releases/download/v1.2.1/revealgo_1.2.1_Linux-ARM.tar.gz"
      sha256 "ae376901902b191d94de0b801901616431409d8f1c22ead8c56c440957760262"

      def install
        bin.install "revealgo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yusukebe/revealgo/releases/download/v1.2.1/revealgo_1.2.1_Linux-64bit.tar.gz"
      sha256 "068f61a155eb2c8a7e9b25762435623e20d594e3df43cae6b26940ec28f0c8f0"

      def install
        bin.install "revealgo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yusukebe/revealgo/releases/download/v1.2.1/revealgo_1.2.1_Linux-ARM64.tar.gz"
      sha256 "54857e188e1c464beffa7247ae396a3d36aaceaa2ebce6126aa2a0696b2ad664"

      def install
        bin.install "revealgo"
      end
    end
  end
end
