# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rj < Formula
  desc "CLI for printing HTTP Response as JSON."
  homepage "https://github.com/yusukebe/rj"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yusukebe/rj/releases/download/v0.1.1/rj_darwin_arm64.tar.gz"
      sha256 "4cce214c8e9415acbac0bf361afa17f55b85c11d5de4c1ccf44ea30ad3e68e39"

      def install
        bin.install "rj"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yusukebe/rj/releases/download/v0.1.1/rj_darwin_amd64.tar.gz"
      sha256 "9eb35dd2181eeafbc6f67bdfe3e24b457066531c725056527c951d14fc1407d8"

      def install
        bin.install "rj"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yusukebe/rj/releases/download/v0.1.1/rj_linux_arm64.tar.gz"
      sha256 "75cfb7591680b9947bdccf674890758fe07a98aadc81b50af366eb3a08a7d4b4"

      def install
        bin.install "rj"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yusukebe/rj/releases/download/v0.1.1/rj_linux_amd64.tar.gz"
      sha256 "6e2f0195e12e5fbd73de4ec75872642844fe8976a17358a4a563b8e8347c4ea9"

      def install
        bin.install "rj"
      end
    end
  end
end
