# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rj < Formula
  desc "CLI for printing HTTP Response as JSON."
  homepage "https://github.com/yusukebe/rj"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yusukebe/rj/releases/download/v0.1.2/rj_darwin_arm64.tar.gz"
      sha256 "e42d682a85c7d2aa8c8c420224c83891ca0177e0c278a89072d8f968e76b77f4"

      def install
        bin.install "rj"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yusukebe/rj/releases/download/v0.1.2/rj_darwin_amd64.tar.gz"
      sha256 "bce1d2d8b095b17b8229d8bf2185717dfefa5ee083f63d4b52535b25b118005f"

      def install
        bin.install "rj"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yusukebe/rj/releases/download/v0.1.2/rj_linux_arm64.tar.gz"
      sha256 "1462db82afc15fdc0be5cababc85a2b2acc8abd8f511a5bc78eda4cdfcbcb63b"

      def install
        bin.install "rj"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yusukebe/rj/releases/download/v0.1.2/rj_linux_amd64.tar.gz"
      sha256 "842759a9225fa1b412694377baa71a2e9cc596b42ade2a49a652f5089cc678b7"

      def install
        bin.install "rj"
      end
    end
  end
end
