# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rj < Formula
  desc "CLI for printing HTTP Response as JSON."
  homepage "https://github.com/yusukebe/rj"
  version "0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yusukebe/rj/releases/download/v0.0.8/rj_darwin_arm64.tar.gz"
      sha256 "03b68cf086f8d2dfbfe041153b9e434e0850bf3640c268ca4080aa43ac7ccc82"

      def install
        bin.install "rj"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yusukebe/rj/releases/download/v0.0.8/rj_darwin_amd64.tar.gz"
      sha256 "b9c5b274ebe2b4173942c381dbbed05ff80d53e1830f31b27dc3f0e8fa654bb8"

      def install
        bin.install "rj"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yusukebe/rj/releases/download/v0.0.8/rj_linux_arm64.tar.gz"
      sha256 "8df6525f1bac39720465a03ad66436f447de42682a2ce98a2acded1c4a853fda"

      def install
        bin.install "rj"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yusukebe/rj/releases/download/v0.0.8/rj_linux_amd64.tar.gz"
      sha256 "6ebc5b33a108b2c7e6c8c7b8144961f40c1dd12403b2c4f197bacc973f78670f"

      def install
        bin.install "rj"
      end
    end
  end
end
